# Conda environment for Gammapy version 1.3rc1
# Install:    conda env create -f gammapy-1.3rc1-environment.yml
# Activate:   conda activate gammapy-1.3rc1
# Deactivate: conda deactivate

name: gammapy-1.3rc1

channels:
  - conda-forge
  - https://cxc.cfa.harvard.edu/conda/sherpa

variables:
  PYTHONNOUSERSITE: "1"

dependencies:
  - python=3.11
  - ipython=8.27
  - cython
  - jupyter
  - jupyterlab=4.0
  - pyyaml=6.0
  - click=8.1
  - numpy=1.26
  - scipy=1.12
  - pandas=2.2
  - matplotlib=3.9
  - astropy=6.0
  - regions=0.8
  - iminuit=2.24
  - sherpa==4.17
  - healpy=1.16
  - naima=0.10
  - pydantic=2.5
  - emcee=3.1
  - corner=2.2
  - pip
  - requests
  - tqdm
  - pip:
    - gammapy==1.3rc1
    - ray[default]==2.35
