# Conda environment for Gammapy version 0.19
# Install:    conda env create -f gammapy-0.19-environment.yml
# Activate:   conda activate gammapy-0.19
# Deactivate: conda deactivate

name: gammapy-0.19

channels:
  - conda-forge
  - sherpa

dependencies:
  - gammapy=0.19
  - python=3.7.0
  - ipython=7.10
  # Cython isn't really needed when installing binaries,
  # but it is convenient for users that build from source
  - cython
  - jupyter
  - jupyterlab=2.0.1
  - pyyaml=5.2
  - click=7.0
  - numpy=1.21.4
  - scipy=1.7.1
  - pandas=1.3.4
  - matplotlib=3.4.3
  - astropy=4.3.1
  - regions=0.5
  - iminuit=2.8.4
  - sherpa=4.14.0
  - healpy=1.15
  - naima=0.9.1
  - pydantic=1.8.2
  - emcee=2.2.1
  - corner=2.0
  - parfive=1.0
  - pip
  - requests
